### ISSUE TITLE
Suitesparse linking issue

### ISSUE THREAD

**Issue by jmogali** [PetterS/SuiteSparse#2]
Hi,
      I am trying to link suitesparse with a c++ project of mine. However, upon compiling my project, I get the following error-:
/usr/bin/ld: //usr/local/lib/libcholmod.a(cholmod_super_numeric.o): undefined reference to symbol 'zpotrf_'
//usr/lib/liblapack.so.3: error adding symbols: DSO missing from command line

Any idea what I may be doing wrong. FYI, i directly used the latest Suitesparse source from Tim Davis's site. His package builds perfectly on my machine (ubunut 14.04). If it may be of any help, my project also uses IPOPT which also links with lapack and blas.

Thanks,
jayanth

**Comment by PetterS** [comment]
Sorry, I don’t know.
